utg =   [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [0, [0, set()]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]]] 

utg1 =  [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [0, [0, set()]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]]]

lj =    [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [1, [4, {'Ad7d', 'As7s', 'Ah7h', 'Ac7c'}]], 
                [1, [4, {'Ad6d', 'Ah6h', 'Ac6c', 'As6s'}]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [1, [4, {'Ad3d', 'As3s', 'Ac3c', 'Ah3h'}]], 
                [1, [4, {'Ah2h', 'As2s', 'Ac2c', 'Ad2d'}]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [1, [4, {'Kd9d', 'Kc9c', 'Kh9h', 'Ks9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [1, [12, {'KdQs', 'KdQc', 'KhQc', 'KhQd', 'KcQs', 'KhQs', 'KsQd', 'KsQh', 'KsQc', 'KdQh', 'KcQd', 'KcQh'}]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [1, [4, {'Qs9s', 'Qd9d', 'Qh9h', 'Qc9c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsJc', 'AdJc', 'AhJc', 'AcJd', 'AcJs', 'AdJs', 'AhJd', 'AhJs', 'AsJh', 'AsJd', 'AdJh', 'AcJh'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [1, [4, {'Jh9h', 'Jc9c', 'Js9s', 'Jd9d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [1, [4, {'7d6d', '7c6c', '7s6s', '7h6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]]] 

hj =    [    [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [1, [4, {'Ad7d', 'As7s', 'Ah7h', 'Ac7c'}]], 
                [1, [4, {'Ad6d', 'Ah6h', 'Ac6c', 'As6s'}]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [1, [4, {'Ad3d', 'As3s', 'Ac3c', 'Ah3h'}]], 
                [1, [4, {'Ah2h', 'As2s', 'Ac2c', 'Ad2d'}]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [1, [4, {'Kd9d', 'Kc9c', 'Kh9h', 'Ks9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [1, [12, {'KdQs', 'KdQc', 'KhQc', 'KhQd', 'KcQs', 'KhQs', 'KsQd', 'KsQh', 'KsQc', 'KdQh', 'KcQd', 'KcQh'}]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [1, [4, {'Qs9s', 'Qd9d', 'Qh9h', 'Qc9c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsJc', 'AdJc', 'AhJc', 'AcJd', 'AcJs', 'AdJs', 'AhJd', 'AhJs', 'AsJh', 'AsJd', 'AdJh', 'AcJh'}]], 
                [1, [12, {'KdJs', 'KsJd', 'KhJd', 'KsJh', 'KcJh', 'KsJc', 'KcJs', 'KdJh', 'KhJs', 'KhJc', 'KcJd', 'KdJc'}]], 
                [1, [12, {'QcJs', 'QdJh', 'QcJd', 'QhJc', 'QsJc', 'QsJh', 'QhJs', 'QsJd', 'QdJs', 'QhJd', 'QcJh', 'QdJc'}]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [1, [4, {'Jh9h', 'Jc9c', 'Js9s', 'Jd9d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsTc', 'AhTd', 'AcTd', 'AdTs', 'AhTs', 'AsTh', 'AsTd', 'AdTc', 'AdTh', 'AcTs', 'AhTc', 'AcTh'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [1, [4, {'7d6d', '7c6c', '7s6s', '7h6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [1, [4, {'6c5c', '6d5d', '6s5s', '6h5h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'4h4s', '4c4h', '4d4h', '4c4s', '4d4s', '4c4d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'3h3s', '3c3d', '3d3s', '3d3h', '3c3h', '3c3s'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'2c2d', '2c2h', '2h2s', '2d2h', '2d2s', '2c2s'}]]]] 

co =    [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [1, [4, {'Ad7d', 'As7s', 'Ah7h', 'Ac7c'}]], 
                [1, [4, {'Ad6d', 'Ah6h', 'Ac6c', 'As6s'}]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [1, [4, {'Ad3d', 'As3s', 'Ac3c', 'Ah3h'}]], 
                [1, [4, {'Ah2h', 'As2s', 'Ac2c', 'Ad2d'}]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [1, [4, {'Kd9d', 'Kc9c', 'Kh9h', 'Ks9s'}]], 
                [1, [4, {'Ks8s', 'Kd8d', 'Kh8h', 'Kc8c'}]], 
                [1, [4, {'Kc7c', 'Ks7s', 'Kd7d', 'Kh7h'}]], 
                [1, [4, {'Ks6s', 'Kc6c', 'Kh6h', 'Kd6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [1, [12, {'KdQs', 'KdQc', 'KhQc', 'KhQd', 'KcQs', 'KhQs', 'KsQd', 'KsQh', 'KsQc', 'KdQh', 'KcQd', 'KcQh'}]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [1, [4, {'Qs9s', 'Qd9d', 'Qh9h', 'Qc9c'}]], 
                [1, [4, {'Qc8c', 'Qh8h', 'Qs8s', 'Qd8d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsJc', 'AdJc', 'AhJc', 'AcJd', 'AcJs', 'AdJs', 'AhJd', 'AhJs', 'AsJh', 'AsJd', 'AdJh', 'AcJh'}]], 
                [1, [12, {'KdJs', 'KsJd', 'KhJd', 'KsJh', 'KcJh', 'KsJc', 'KcJs', 'KdJh', 'KhJs', 'KhJc', 'KcJd', 'KdJc'}]], 
                [1, [12, {'QcJs', 'QdJh', 'QcJd', 'QhJc', 'QsJc', 'QsJh', 'QhJs', 'QsJd', 'QdJs', 'QhJd', 'QcJh', 'QdJc'}]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [1, [4, {'Jh9h', 'Jc9c', 'Js9s', 'Jd9d'}]], 
                [1, [4, {'Jc8c', 'Js8s', 'Jd8d', 'Jh8h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsTc', 'AhTd', 'AcTd', 'AdTs', 'AhTs', 'AsTh', 'AsTd', 'AdTc', 'AdTh', 'AcTs', 'AhTc', 'AcTh'}]], 
                [1, [12, {'KdTh', 'KsTc', 'KdTc', 'KdTs', 'KcTd', 'KsTd', 'KsTh', 'KhTd', 'KcTs', 'KcTh', 'KhTs', 'KhTc'}]], 
                [1, [12, {'QdTh', 'QcTs', 'QsTh', 'QhTd', 'QcTd', 'QcTh', 'QdTs', 'QsTc', 'QhTs', 'QsTd', 'QhTc', 'QdTc'}]], 
                [1, [12, {'JdTh', 'JhTs', 'JhTc', 'JcTd', 'JsTd', 'JhTd', 'JdTc', 'JdTs', 'JsTc', 'JcTs', 'JsTh', 'JcTh'}]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [1, [4, {'Th8h', 'Td8d', 'Ts8s', 'Tc8c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [1, [4, {'9h7h', '9d7d', '9c7c', '9s7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [1, [4, {'8d6d', '8c6c', '8s6s', '8h6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [1, [4, {'7d6d', '7c6c', '7s6s', '7h6h'}]], 
                [1, [4, {'7s5s', '7d5d', '7h5h', '7c5c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [1, [4, {'6c5c', '6d5d', '6s5s', '6h5h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [1, [4, {'5c4c', '5s4s', '5h4h', '5d4d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'4h4s', '4c4h', '4d4h', '4c4s', '4d4s', '4c4d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'3h3s', '3c3d', '3d3s', '3d3h', '3c3h', '3c3s'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'2c2d', '2c2h', '2h2s', '2d2h', '2d2s', '2c2s'}]]]] 

btn =   [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [1, [4, {'Ad7d', 'As7s', 'Ah7h', 'Ac7c'}]], 
                [1, [4, {'Ad6d', 'Ah6h', 'Ac6c', 'As6s'}]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [1, [4, {'Ad3d', 'As3s', 'Ac3c', 'Ah3h'}]], 
                [1, [4, {'Ah2h', 'As2s', 'Ac2c', 'Ad2d'}]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [1, [4, {'Kd9d', 'Kc9c', 'Kh9h', 'Ks9s'}]], 
                [1, [4, {'Ks8s', 'Kd8d', 'Kh8h', 'Kc8c'}]], 
                [1, [4, {'Kc7c', 'Ks7s', 'Kd7d', 'Kh7h'}]], 
                [1, [4, {'Ks6s', 'Kc6c', 'Kh6h', 'Kd6d'}]], 
                [1, [4, {'Ks5s', 'Kh5h', 'Kc5c', 'Kd5d'}]], 
                [1, [4, {'Kh4h', 'Ks4s', 'Kc4c', 'Kd4d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [1, [12, {'KdQs', 'KdQc', 'KhQc', 'KhQd', 'KcQs', 'KhQs', 'KsQd', 'KsQh', 'KsQc', 'KdQh', 'KcQd', 'KcQh'}]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [1, [4, {'Qs9s', 'Qd9d', 'Qh9h', 'Qc9c'}]], 
                [1, [4, {'Qc8c', 'Qh8h', 'Qs8s', 'Qd8d'}]], 
                [1, [4, {'Qc7c', 'Qd7d', 'Qs7s', 'Qh7h'}]], 
                [1, [4, {'Qd6d', 'Qc6c', 'Qs6s', 'Qh6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsJc', 'AdJc', 'AhJc', 'AcJd', 'AcJs', 'AdJs', 'AhJd', 'AhJs', 'AsJh', 'AsJd', 'AdJh', 'AcJh'}]], 
                [1, [12, {'KdJs', 'KsJd', 'KhJd', 'KsJh', 'KcJh', 'KsJc', 'KcJs', 'KdJh', 'KhJs', 'KhJc', 'KcJd', 'KdJc'}]], 
                [1, [12, {'QcJs', 'QdJh', 'QcJd', 'QhJc', 'QsJc', 'QsJh', 'QhJs', 'QsJd', 'QdJs', 'QhJd', 'QcJh', 'QdJc'}]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [1, [4, {'Jh9h', 'Jc9c', 'Js9s', 'Jd9d'}]], 
                [1, [4, {'Jc8c', 'Js8s', 'Jd8d', 'Jh8h'}]], 
                [1, [4, {'Jc7c', 'Jh7h', 'Jd7d', 'Js7s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsTc', 'AhTd', 'AcTd', 'AdTs', 'AhTs', 'AsTh', 'AsTd', 'AdTc', 'AdTh', 'AcTs', 'AhTc', 'AcTh'}]], 
                [1, [12, {'KdTh', 'KsTc', 'KdTc', 'KdTs', 'KcTd', 'KsTd', 'KsTh', 'KhTd', 'KcTs', 'KcTh', 'KhTs', 'KhTc'}]], 
                [1, [12, {'QdTh', 'QcTs', 'QsTh', 'QhTd', 'QcTd', 'QcTh', 'QdTs', 'QsTc', 'QhTs', 'QsTd', 'QhTc', 'QdTc'}]], 
                [1, [12, {'JdTh', 'JhTs', 'JhTc', 'JcTd', 'JsTd', 'JhTd', 'JdTc', 'JdTs', 'JsTc', 'JcTs', 'JsTh', 'JcTh'}]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [1, [4, {'Th8h', 'Td8d', 'Ts8s', 'Tc8c'}]], 
                [1, [4, {'Ts7s', 'Tc7c', 'Th7h', 'Td7d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad9c', 'As9h', 'Ah9d', 'As9d', 'Ac9d', 'Ah9c', 'Ad9s', 'Ac9h', 'Ad9h', 'Ac9s', 'Ah9s', 'As9c'}]], 
                [1, [12, {'Kd9s', 'Kc9h', 'Kc9d', 'Kh9d', 'Kh9c', 'Ks9c', 'Ks9h', 'Kc9s', 'Kd9h', 'Kh9s', 'Kd9c', 'Ks9d'}]], 
                [1, [12, {'Qs9h', 'Qd9h', 'Qs9d', 'Qs9c', 'Qc9h', 'Qh9s', 'Qd9c', 'Qh9c', 'Qh9d', 'Qc9s', 'Qd9s', 'Qc9d'}]], 
                [1, [12, {'Jh9s', 'Jd9c', 'Jh9d', 'Jc9h', 'Jc9s', 'Jh9c', 'Jd9s', 'Js9h', 'Js9c', 'Jc9d', 'Jd9h', 'Js9d'}]], 
                [1, [12, {'Td9c', 'Tc9d', 'Ts9c', 'Ts9d', 'Th9c', 'Th9s', 'Td9s', 'Tc9s', 'Ts9h', 'Td9h', 'Th9d', 'Tc9h'}]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [1, [4, {'9h7h', '9d7d', '9c7c', '9s7s'}]], 
                [1, [4, {'9h6h', '9c6c', '9s6s', '9d6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ah8c', 'Ad8s', 'Ac8h', 'Ah8d', 'Ad8c', 'As8d', 'As8h', 'Ad8h', 'Ac8d', 'Ac8s', 'As8c', 'Ah8s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [1, [4, {'8d6d', '8c6c', '8s6s', '8h6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ah7s', 'As7c', 'Ac7d', 'As7h', 'Ah7d', 'Ad7h', 'Ad7c', 'Ah7c', 'Ac7s', 'Ac7h', 'Ad7s', 'As7d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [1, [4, {'7d6d', '7c6c', '7s6s', '7h6h'}]], 
                [1, [4, {'7s5s', '7d5d', '7h5h', '7c5c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad6s', 'Ad6h', 'Ac6h', 'Ac6s', 'As6h', 'Ah6d', 'Ah6c', 'Ah6s', 'Ad6c', 'As6c', 'As6d', 'Ac6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [1, [4, {'6c5c', '6d5d', '6s5s', '6h5h'}]], 
                [1, [4, {'6d4d', '6h4h', '6s4s', '6c4c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ac5h', 'Ad5c', 'Ah5d', 'As5h', 'As5d', 'Ac5d', 'Ac5s', 'Ad5s', 'Ah5s', 'As5c', 'Ah5c', 'Ad5h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [1, [4, {'5c4c', '5s4s', '5h4h', '5d4d'}]], 
                [1, [4, {'5h3h', '5c3c', '5s3s', '5d3d'}]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad4h', 'Ah4d', 'Ac4h', 'Ad4s', 'As4d', 'Ac4d', 'Ah4s', 'As4c', 'Ah4c', 'Ad4c', 'As4h', 'Ac4s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'4h4s', '4c4h', '4d4h', '4c4s', '4d4s', '4c4d'}]], 
                [1, [4, {'4s3s', '4c3c', '4h3h', '4d3d'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'3h3s', '3c3d', '3d3s', '3d3h', '3c3h', '3c3s'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'2c2d', '2c2h', '2h2s', '2d2h', '2d2s', '2c2s'}]]]] 

sb =    [   [   [1, [6, {'AdAs', 'AcAh', 'AcAs', 'AdAh', 'AcAd', 'AhAs'}]], 
                [1, [4, {'AdKd', 'AsKs', 'AcKc', 'AhKh'}]], 
                [1, [4, {'AsQs', 'AcQc', 'AhQh', 'AdQd'}]], 
                [1, [4, {'AhJh', 'AcJc', 'AsJs', 'AdJd'}]], 
                [1, [4, {'AdTd', 'AcTc', 'AsTs', 'AhTh'}]], 
                [1, [4, {'Ah9h', 'Ad9d', 'As9s', 'Ac9c'}]], 
                [1, [4, {'As8s', 'Ad8d', 'Ac8c', 'Ah8h'}]], 
                [1, [4, {'Ad7d', 'As7s', 'Ah7h', 'Ac7c'}]], 
                [1, [4, {'Ad6d', 'Ah6h', 'Ac6c', 'As6s'}]], 
                [1, [4, {'Ah5h', 'As5s', 'Ac5c', 'Ad5d'}]], 
                [1, [4, {'As4s', 'Ah4h', 'Ac4c', 'Ad4d'}]], 
                [1, [4, {'Ad3d', 'As3s', 'Ac3c', 'Ah3h'}]], 
                [1, [4, {'Ah2h', 'As2s', 'Ac2c', 'Ad2d'}]]], 
            [   [1, [12, {'AsKc', 'AsKd', 'AdKc', 'AcKs', 'AdKs', 'AdKh', 'AhKs', 'AsKh', 'AhKd', 'AhKc', 'AcKh', 'AcKd'}]], 
                [1, [6, {'KcKs', 'KdKh', 'KcKh', 'KhKs', 'KcKd', 'KdKs'}]], 
                [1, [4, {'KcQc', 'KhQh', 'KsQs', 'KdQd'}]], 
                [1, [4, {'KhJh', 'KsJs', 'KdJd', 'KcJc'}]], 
                [1, [4, {'KdTd', 'KsTs', 'KhTh', 'KcTc'}]], 
                [1, [4, {'Kd9d', 'Kc9c', 'Kh9h', 'Ks9s'}]], 
                [1, [4, {'Ks8s', 'Kd8d', 'Kh8h', 'Kc8c'}]], 
                [1, [4, {'Kc7c', 'Ks7s', 'Kd7d', 'Kh7h'}]], 
                [1, [4, {'Ks6s', 'Kc6c', 'Kh6h', 'Kd6d'}]], 
                [1, [4, {'Ks5s', 'Kh5h', 'Kc5c', 'Kd5d'}]], 
                [1, [4, {'Kh4h', 'Ks4s', 'Kc4c', 'Kd4d'}]], 
                [1, [4, {'Kd3d', 'Kc3c', 'Kh3h', 'Ks3s'}]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AcQd', 'AsQd', 'AsQc', 'AhQc', 'AcQh', 'AhQd', 'AdQs', 'AcQs', 'AdQc', 'AsQh', 'AhQs', 'AdQh'}]], 
                [1, [12, {'KdQs', 'KdQc', 'KhQc', 'KhQd', 'KcQs', 'KhQs', 'KsQd', 'KsQh', 'KsQc', 'KdQh', 'KcQd', 'KcQh'}]], 
                [1, [6, {'QhQs', 'QdQs', 'QcQs', 'QcQd', 'QdQh', 'QcQh'}]], 
                [1, [4, {'QdJd', 'QcJc', 'QhJh', 'QsJs'}]], 
                [1, [4, {'QdTd', 'QsTs', 'QhTh', 'QcTc'}]], 
                [1, [4, {'Qs9s', 'Qd9d', 'Qh9h', 'Qc9c'}]], 
                [1, [4, {'Qc8c', 'Qh8h', 'Qs8s', 'Qd8d'}]], 
                [1, [4, {'Qc7c', 'Qd7d', 'Qs7s', 'Qh7h'}]], 
                [1, [4, {'Qd6d', 'Qc6c', 'Qs6s', 'Qh6h'}]], 
                [1, [4, {'Qd5d', 'Qc5c', 'Qh5h', 'Qs5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsJc', 'AdJc', 'AhJc', 'AcJd', 'AcJs', 'AdJs', 'AhJd', 'AhJs', 'AsJh', 'AsJd', 'AdJh', 'AcJh'}]], 
                [1, [12, {'KdJs', 'KsJd', 'KhJd', 'KsJh', 'KcJh', 'KsJc', 'KcJs', 'KdJh', 'KhJs', 'KhJc', 'KcJd', 'KdJc'}]], 
                [1, [12, {'QcJs', 'QdJh', 'QcJd', 'QhJc', 'QsJc', 'QsJh', 'QhJs', 'QsJd', 'QdJs', 'QhJd', 'QcJh', 'QdJc'}]], 
                [1, [6, {'JdJh', 'JcJh', 'JhJs', 'JcJs', 'JcJd', 'JdJs'}]], 
                [1, [4, {'JdTd', 'JhTh', 'JcTc', 'JsTs'}]], 
                [1, [4, {'Jh9h', 'Jc9c', 'Js9s', 'Jd9d'}]], 
                [1, [4, {'Jc8c', 'Js8s', 'Jd8d', 'Jh8h'}]], 
                [1, [4, {'Jc7c', 'Jh7h', 'Jd7d', 'Js7s'}]], 
                [1, [4, {'Jd6d', 'Jc6c', 'Js6s', 'Jh6h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'AsTc', 'AhTd', 'AcTd', 'AdTs', 'AhTs', 'AsTh', 'AsTd', 'AdTc', 'AdTh', 'AcTs', 'AhTc', 'AcTh'}]], 
                [1, [12, {'KdTh', 'KsTc', 'KdTc', 'KdTs', 'KcTd', 'KsTd', 'KsTh', 'KhTd', 'KcTs', 'KcTh', 'KhTs', 'KhTc'}]], 
                [1, [12, {'QdTh', 'QcTs', 'QsTh', 'QhTd', 'QcTd', 'QcTh', 'QdTs', 'QsTc', 'QhTs', 'QsTd', 'QhTc', 'QdTc'}]], 
                [1, [12, {'JdTh', 'JhTs', 'JhTc', 'JcTd', 'JsTd', 'JhTd', 'JdTc', 'JdTs', 'JsTc', 'JcTs', 'JsTh', 'JcTh'}]], 
                [1, [6, {'ThTs', 'TdTh', 'TcTd', 'TcTs', 'TcTh', 'TdTs'}]], 
                [1, [4, {'Tc9c', 'Td9d', 'Th9h', 'Ts9s'}]], 
                [1, [4, {'Th8h', 'Td8d', 'Ts8s', 'Tc8c'}]], 
                [1, [4, {'Ts7s', 'Tc7c', 'Th7h', 'Td7d'}]], 
                [1, [4, {'Tc6c', 'Th6h', 'Ts6s', 'Td6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad9c', 'As9h', 'Ah9d', 'As9d', 'Ac9d', 'Ah9c', 'Ad9s', 'Ac9h', 'Ad9h', 'Ac9s', 'Ah9s', 'As9c'}]], 
                [1, [12, {'Kd9s', 'Kc9h', 'Kc9d', 'Kh9d', 'Kh9c', 'Ks9c', 'Ks9h', 'Kc9s', 'Kd9h', 'Kh9s', 'Kd9c', 'Ks9d'}]], 
                [1, [12, {'Qs9h', 'Qd9h', 'Qs9d', 'Qs9c', 'Qc9h', 'Qh9s', 'Qd9c', 'Qh9c', 'Qh9d', 'Qc9s', 'Qd9s', 'Qc9d'}]], 
                [1, [12, {'Jh9s', 'Jd9c', 'Jh9d', 'Jc9h', 'Jc9s', 'Jh9c', 'Jd9s', 'Js9h', 'Js9c', 'Jc9d', 'Jd9h', 'Js9d'}]], 
                [1, [12, {'Td9c', 'Tc9d', 'Ts9c', 'Ts9d', 'Th9c', 'Th9s', 'Td9s', 'Tc9s', 'Ts9h', 'Td9h', 'Th9d', 'Tc9h'}]], 
                [1, [6, {'9c9s', '9c9d', '9c9h', '9d9h', '9h9s', '9d9s'}]], 
                [1, [4, {'9h8h', '9c8c', '9s8s', '9d8d'}]], 
                [1, [4, {'9h7h', '9d7d', '9c7c', '9s7s'}]], 
                [1, [4, {'9h6h', '9c6c', '9s6s', '9d6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ah8c', 'Ad8s', 'Ac8h', 'Ah8d', 'Ad8c', 'As8d', 'As8h', 'Ad8h', 'Ac8d', 'Ac8s', 'As8c', 'Ah8s'}]], 
                [1, [12, {'Kh8d', 'Ks8d', 'Kc8h', 'Ks8h', 'Kd8h', 'Kc8d', 'Ks8c', 'Kh8c', 'Kd8s', 'Kh8s', 'Kd8c', 'Kc8s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'8d8s', '8h8s', '8c8s', '8c8h', '8d8h', '8c8d'}]], 
                [1, [4, {'8c7c', '8d7d', '8h7h', '8s7s'}]], 
                [1, [4, {'8d6d', '8c6c', '8s6s', '8h6h'}]], 
                [1, [4, {'8d5d', '8h5h', '8c5c', '8s5s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ah7s', 'As7c', 'Ac7d', 'As7h', 'Ah7d', 'Ad7h', 'Ad7c', 'Ah7c', 'Ac7s', 'Ac7h', 'Ad7s', 'As7d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'7c7d', '7c7h', '7c7s', '7d7h', '7h7s', '7d7s'}]], 
                [1, [4, {'7d6d', '7c6c', '7s6s', '7h6h'}]], 
                [1, [4, {'7s5s', '7d5d', '7h5h', '7c5c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad6s', 'Ad6h', 'Ac6h', 'Ac6s', 'As6h', 'Ah6d', 'Ah6c', 'Ah6s', 'Ad6c', 'As6c', 'As6d', 'Ac6d'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'6c6d', '6c6s', '6c6h', '6d6s', '6d6h', '6h6s'}]], 
                [1, [4, {'6c5c', '6d5d', '6s5s', '6h5h'}]], 
                [1, [4, {'6d4d', '6h4h', '6s4s', '6c4c'}]], 
                [0, [0, set()]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ac5h', 'Ad5c', 'Ah5d', 'As5h', 'As5d', 'Ac5d', 'Ac5s', 'Ad5s', 'Ah5s', 'As5c', 'Ah5c', 'Ad5h'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'5c5d', '5c5h', '5c5s', '5d5s', '5d5h', '5h5s'}]], 
                [1, [4, {'5c4c', '5s4s', '5h4h', '5d4d'}]], 
                [1, [4, {'5h3h', '5c3c', '5s3s', '5d3d'}]], 
                [0, [0, set()]]], 
            [   [1, [12, {'Ad4h', 'Ah4d', 'Ac4h', 'Ad4s', 'As4d', 'Ac4d', 'Ah4s', 'As4c', 'Ah4c', 'Ad4c', 'As4h', 'Ac4s'}]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'4h4s', '4c4h', '4d4h', '4c4s', '4d4s', '4c4d'}]], 
                [1, [4, {'4s3s', '4c3c', '4h3h', '4d3d'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'3h3s', '3c3d', '3d3s', '3d3h', '3c3h', '3c3s'}]], 
                [0, [0, set()]]], 
            [   [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [0, [0, set()]], 
                [1, [6, {'2c2d', '2c2h', '2h2s', '2d2h', '2d2s', '2c2s'}]]]]
